-   repo: git://github.com/FalconSocial/pre-commit-python-sorter
    sha: b57843b0b874df1d16eb0bef00b868792cb245c2
    hooks:
    -   id: python-import-sorter
        args:
        - --silent-overwrite
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 5bf6c09bfa1297d3692cadd621ef95f1284e33c0
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-xml
    -   id: check-yaml
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: pretty-format-json
        args:
        - --autofix
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: flake8
        args:
        - --max-line-length=80
        - --ignore=E226,E731,F405
